#!/bin/bash
# Massive Network Game Object Server
# autorestart Script

while :
do
	echo "MaNGOS daemon restarted"
	echo `date` >> crash.log &
	./mangosd | tail -n 20 >> crash.log
	echo " " >> crash.log &
	pid=`ps ax | awk '($5 ~ /mangosd/) { print $1 }'`
	wait $pid
	exitcode=`cat mangos-exit.log`
	echo "Exit code = " "$exitcode"
	#Use CLI command "server shutdown 30" to exit autorestart Script
	if [ "$exitcode" -eq 0 ]; then
        	echo `date` ", MaNGOS daemon ended." >> serverlog
		echo "Goodbye!"
		exit 0
	fi
        echo `date` ", MaNGOS daemon crashed and restarted." >> serverlog
done
